# Configuração oficial para Next.js no Netlify
[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_PUBLIC_API_URL = "https://mwp-production-6b45.up.railway.app"